# Generated by Django 4.2.3 on 2023-12-07 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000, unique=True)),
                ('is_true', models.BooleanField(default=True)),
                ('climate_paramter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climateparametre')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('desription', models.CharField(max_length=1000)),
                ('climate_paramter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climateparametre')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000, unique=True)),
                ('image', models.ImageField(null=True, upload_to='user_images')),
                ('climate_paramter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climateparametre')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desription', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('climate_paramter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climateparametre')),
            ],
        ),
    ]
