# Generated by Django 4.2.3 on 2023-12-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('desription', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(null=True)),
                ('climate_paramter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.climateparametre')),
            ],
        ),
        migrations.RemoveField(
            model_name='idea',
            name='climate_paramter',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
    ]
