# Generated by Django 4.2.3 on 2023-12-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solutions_remove_idea_climate_paramter_delete_event_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClimateParametre',
            new_name='Factors',
        ),
    ]
