# Generated by Django 4.2.3 on 2023-12-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_climateparametre_factors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factors',
            old_name='desription',
            new_name='description',
        ),
    ]
