# Generated by Django 4.2.3 on 2023-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_desription_factors_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='climate_paramter',
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
