# Generated by Django 4.2.3 on 2023-12-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_information_climate_paramter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='user_images'),
        ),
    ]
