# Generated by Django 4.2.3 on 2023-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_solutions_climate_paramter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
